#name: Sync Image to Aliyun  Example
# 
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
# 
#jobs:
#  build:
#    runs-on: ubuntu-latest
# 
#    steps:
#    - name: Git pull
#      uses: actions/checkout@v3
#      
#    - name: Set up Docker Buildx
#      uses: southamerica-east1-docker.pkg.dev/k8s-artifacts-prod/images/kubectl-amd64@v1.30.3
# 
#    - name: Login to Docker Hub
#      uses: docker/login-action@v2.2.0
#      with:
#        registry: registry.cn-hangzhou.aliyuncs.com
#        username: l240250076
#        password: Aisino@2024
#        logout: false
#        
#    - name: Use Skopeo Tools Sync Image to Docker Hub
#      run: |
#        skopeo copy docker://southamerica-east1-docker.pkg.dev/k8s-artifacts-prod/images/kubectl-amd64:v1.30.3 docker://registry.cn-hangzhou.aliyuncs.com/liutianji/kube-apiserver:v1.30.3
#      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
