name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: l240250076
          password: Aisino@2024
      - name: Docker pull and push
        run: |
          docker pull python:2.7
          
          docker tag python:2.7 registry.cn-hangzhou.aliyuncs.com/liutianji/python:2.7
          
          docker push registry.cn-hangzhou.aliyuncs.com/liutianji/python:2.7
