name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: l240250076
          password: Aisino@2024
      - name: Docker pull and push
        run: |
          docker pull  quay.io/calico/node:v3.24.5
          docker pull  k8s.gcr.io/kube-proxy:v1.26.4
          docker pull  k8s.gcr.io/dns/k8s-dns-node-cache:1.22.18
          
          docker tag quay.io/calico/node:v3.24.5 registry.cn-hangzhou.aliyuncs.com/liutianji/node:v3.24.5
          docker tag k8s.gcr.io/kube-proxy:v1.26.4 registry.cn-hangzhou.aliyuncs.com/liutianji/kube-proxy:v1.26.4
          docker tag k8s.gcr.io/dns/k8s-dns-node-cache:1.22.18 registry.cn-hangzhou.aliyuncs.com/liutianji/k8s-dns-node-cache:1.22.18

          docker push registry.cn-hangzhou.aliyuncs.com/liutianji/node:v3.24.5
          docker push registry.cn-hangzhou.aliyuncs.com/liutianji/kube-proxy:v1.26.4
          docker push registry.cn-hangzhou.aliyuncs.com/liutianji/k8s-dns-node-cache:1.22.18
